-- ============================================================
-- CARGA DE MODELO Y DATOS — Caso PropiedadCerca (20 tablas)
-- Proyecto Transversal (Evaluación Final Transversal) — BDY1103
-- Taller de Base de Datos — Trabajo grupal, entregas EA1+EA2+EA3
-- ============================================================
-- Ejecuta este script completo en el esquema de trabajo del grupo
-- antes de comenzar. Puedes volver a ejecutarlo para dejar los
-- datos como al inicio (primero elimina las tablas si ya existen,
-- en orden inverso al de creación por las FOREIGN KEY).
--


-- ------------------------------------------------------------
-- DDL (20 tablas)
-- ------------------------------------------------------------

CREATE TABLE comuna (
  comuna_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre    VARCHAR2(60) NOT NULL,
  CONSTRAINT pk_comuna PRIMARY KEY (comuna_id)
);

CREATE TABLE nivel_confianza (
  nivel_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre         VARCHAR2(30) NOT NULL,
  puntos_minimos NUMBER NOT NULL,
  beneficio_pct  NUMBER(5,2) NOT NULL,
  CONSTRAINT pk_nivel_confianza PRIMARY KEY (nivel_id)
);

CREATE TABLE arrendatario (
  arrendatario_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre          VARCHAR2(100) NOT NULL,
  email           VARCHAR2(120) NOT NULL,
  telefono        VARCHAR2(20),
  comuna_id       NUMBER NOT NULL,
  nivel_id        NUMBER NOT NULL,
  fecha_registro  DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_arrendatario PRIMARY KEY (arrendatario_id),
  CONSTRAINT uq_arrendatario_email UNIQUE (email),
  CONSTRAINT fk_arrendatario_comuna FOREIGN KEY (comuna_id) REFERENCES comuna (comuna_id),
  CONSTRAINT fk_arrendatario_nivel FOREIGN KEY (nivel_id) REFERENCES nivel_confianza (nivel_id)
);

CREATE TABLE propietario (
  propietario_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre         VARCHAR2(100) NOT NULL,
  email          VARCHAR2(120) NOT NULL,
  telefono       VARCHAR2(20),
  CONSTRAINT pk_propietario PRIMARY KEY (propietario_id)
);

CREATE TABLE tecnico (
  tecnico_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre          VARCHAR2(100) NOT NULL,
  especialidad    VARCHAR2(20) NOT NULL,
  comuna_base_id  NUMBER NOT NULL,
  disponible      CHAR(1) DEFAULT 'S' NOT NULL,
  rating_promedio NUMBER(3,2) DEFAULT 0 NOT NULL,
  CONSTRAINT pk_tecnico PRIMARY KEY (tecnico_id),
  CONSTRAINT fk_tecnico_comuna FOREIGN KEY (comuna_base_id) REFERENCES comuna (comuna_id),
  CONSTRAINT ck_tecnico_especialidad CHECK (especialidad IN ('GASFITERIA','ELECTRICIDAD','CERRAJERIA','PINTURA')),
  CONSTRAINT ck_tecnico_disponible CHECK (disponible IN ('S','N')),
  CONSTRAINT ck_tecnico_rating CHECK (rating_promedio BETWEEN 0 AND 5)
);

CREATE TABLE edificio (
  edificio_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre      VARCHAR2(100) NOT NULL,
  comuna_id   NUMBER NOT NULL,
  direccion   VARCHAR2(150) NOT NULL,
  CONSTRAINT pk_edificio PRIMARY KEY (edificio_id),
  CONSTRAINT fk_edificio_comuna FOREIGN KEY (comuna_id) REFERENCES comuna (comuna_id)
);

-- categoria_unidad se aplanó como columna de texto de UNIDAD (antes era
-- un catálogo jerárquico aparte, sin ninguna RN apoyada en él).
CREATE TABLE unidad (
  unidad_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
  edificio_id     NUMBER NOT NULL,
  categoria       VARCHAR2(60) NOT NULL,
  propietario_id  NUMBER NOT NULL,
  numero_unidad   VARCHAR2(10) NOT NULL,
  estado          VARCHAR2(15) DEFAULT 'DISPONIBLE' NOT NULL,
  CONSTRAINT pk_unidad PRIMARY KEY (unidad_id),
  CONSTRAINT fk_unidad_edificio FOREIGN KEY (edificio_id) REFERENCES edificio (edificio_id),
  CONSTRAINT fk_unidad_propietario FOREIGN KEY (propietario_id) REFERENCES propietario (propietario_id),
  CONSTRAINT ck_unidad_estado CHECK (estado IN ('DISPONIBLE','ARRENDADA','MANTENCION'))
);

CREATE TABLE amenidad (
  amenidad_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  edificio_id NUMBER NOT NULL,
  nombre      VARCHAR2(60) NOT NULL,
  CONSTRAINT pk_amenidad PRIMARY KEY (amenidad_id),
  CONSTRAINT fk_amenidad_edificio FOREIGN KEY (edificio_id) REFERENCES edificio (edificio_id)
);

CREATE TABLE contrato_arriendo (
  contrato_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
  unidad_id        NUMBER NOT NULL,
  arrendatario_id  NUMBER NOT NULL,
  agente_nombre    VARCHAR2(100),
  fecha_inicio     DATE NOT NULL,
  fecha_termino    DATE NOT NULL,
  monto_mensual    NUMBER(10,2) NOT NULL,
  estado           VARCHAR2(15) DEFAULT 'VIGENTE' NOT NULL,
  CONSTRAINT pk_contrato_arriendo PRIMARY KEY (contrato_id),
  CONSTRAINT fk_contrato_unidad FOREIGN KEY (unidad_id) REFERENCES unidad (unidad_id),
  CONSTRAINT fk_contrato_arrendatario FOREIGN KEY (arrendatario_id) REFERENCES arrendatario (arrendatario_id),
  CONSTRAINT ck_contrato_estado CHECK (estado IN ('VIGENTE','FINALIZADO','CANCELADO')),
  CONSTRAINT ck_contrato_fechas CHECK (fecha_termino > fecha_inicio)
);

-- medio_pago se aplanó como columna de texto de PAGO_ARRIENDO (antes era
-- un catálogo aparte de 3 filas, sin ninguna RN ni objeto obligatorio propio).
CREATE TABLE pago_arriendo (
  pago_id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  contrato_id        NUMBER NOT NULL,
  periodo            VARCHAR2(7) NOT NULL,
  monto              NUMBER(10,2) NOT NULL,
  estado             VARCHAR2(15) DEFAULT 'PENDIENTE' NOT NULL,
  fecha_vencimiento  DATE NOT NULL,
  fecha_pago         DATE,
  medio_pago         VARCHAR2(20),
  CONSTRAINT pk_pago_arriendo PRIMARY KEY (pago_id),
  CONSTRAINT fk_pagoarr_contrato FOREIGN KEY (contrato_id) REFERENCES contrato_arriendo (contrato_id),
  CONSTRAINT ck_pagoarr_medio CHECK (medio_pago IN ('WEBPAY','TRANSFERENCIA','EFECTIVO')),
  CONSTRAINT ck_pagoarr_estado CHECK (estado IN ('PENDIENTE','PAGADO','ATRASADO'))
);

CREATE TABLE reserva_amenidad (
  reserva_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
  amenidad_id     NUMBER NOT NULL,
  arrendatario_id NUMBER NOT NULL,
  fecha           DATE NOT NULL,
  hora_inicio     NUMBER(2) NOT NULL,
  hora_fin        NUMBER(2) NOT NULL,
  estado          VARCHAR2(15) DEFAULT 'CONFIRMADA' NOT NULL,
  CONSTRAINT pk_reserva_amenidad PRIMARY KEY (reserva_id),
  CONSTRAINT fk_reservaamen_amenidad FOREIGN KEY (amenidad_id) REFERENCES amenidad (amenidad_id),
  CONSTRAINT fk_reservaamen_arrendatario FOREIGN KEY (arrendatario_id) REFERENCES arrendatario (arrendatario_id),
  CONSTRAINT ck_reservaamen_estado CHECK (estado IN ('CONFIRMADA','CANCELADA')),
  CONSTRAINT ck_reservaamen_horas CHECK (hora_fin > hora_inicio)
);

CREATE TABLE solicitud_mantencion (
  solicitud_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
  unidad_id       NUMBER NOT NULL,
  arrendatario_id NUMBER NOT NULL,
  tipo_problema   VARCHAR2(20) NOT NULL,
  descripcion     VARCHAR2(300) NOT NULL,
  prioridad       VARCHAR2(10) DEFAULT 'MEDIA' NOT NULL,
  estado          VARCHAR2(15) DEFAULT 'SOLICITADA' NOT NULL,
  tecnico_id      NUMBER,
  fecha_solicitud DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_solicitud_mantencion PRIMARY KEY (solicitud_id),
  CONSTRAINT fk_solmant_unidad FOREIGN KEY (unidad_id) REFERENCES unidad (unidad_id),
  CONSTRAINT fk_solmant_arrendatario FOREIGN KEY (arrendatario_id) REFERENCES arrendatario (arrendatario_id),
  CONSTRAINT fk_solmant_tecnico FOREIGN KEY (tecnico_id) REFERENCES tecnico (tecnico_id),
  CONSTRAINT ck_solmant_tipo CHECK (tipo_problema IN ('GASFITERIA','ELECTRICIDAD','CERRAJERIA','PINTURA')),
  CONSTRAINT ck_solmant_prioridad CHECK (prioridad IN ('BAJA','MEDIA','ALTA')),
  CONSTRAINT ck_solmant_estado CHECK (estado IN ('SOLICITADA','ASIGNADA','EN_PROCESO','RESUELTA','CANCELADA'))
);

CREATE TABLE visita_tecnica (
  visita_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
  solicitud_id     NUMBER NOT NULL,
  tecnico_id       NUMBER NOT NULL,
  fecha_visita     DATE NOT NULL,
  estado           VARCHAR2(15) DEFAULT 'PLANIFICADA' NOT NULL,
  diagnostico      VARCHAR2(300),
  costo_reparacion NUMBER(10,2),
  CONSTRAINT pk_visita_tecnica PRIMARY KEY (visita_id),
  CONSTRAINT fk_visitatec_solicitud FOREIGN KEY (solicitud_id) REFERENCES solicitud_mantencion (solicitud_id),
  CONSTRAINT fk_visitatec_tecnico FOREIGN KEY (tecnico_id) REFERENCES tecnico (tecnico_id),
  CONSTRAINT ck_visitatec_estado CHECK (estado IN ('PLANIFICADA','EN_CURSO','COMPLETADA','FALLIDA'))
);

CREATE TABLE insumo_mantencion (
  insumo_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre         VARCHAR2(100) NOT NULL,
  costo_unitario NUMBER(10,2) NOT NULL,
  CONSTRAINT pk_insumo_mantencion PRIMARY KEY (insumo_id),
  CONSTRAINT ck_insumomant_costo CHECK (costo_unitario > 0)
);

CREATE TABLE bodega_mantencion (
  bodega_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre    VARCHAR2(100) NOT NULL,
  comuna_id NUMBER NOT NULL,
  CONSTRAINT pk_bodega_mantencion PRIMARY KEY (bodega_id),
  CONSTRAINT fk_bodegamant_comuna FOREIGN KEY (comuna_id) REFERENCES comuna (comuna_id)
);

CREATE TABLE inventario_insumo_mantencion (
  bodega_id        NUMBER NOT NULL,
  insumo_id        NUMBER NOT NULL,
  stock_disponible NUMBER NOT NULL,
  CONSTRAINT pk_invinsmant PRIMARY KEY (bodega_id, insumo_id),
  CONSTRAINT fk_invinsmant_bodega FOREIGN KEY (bodega_id) REFERENCES bodega_mantencion (bodega_id),
  CONSTRAINT fk_invinsmant_insumo FOREIGN KEY (insumo_id) REFERENCES insumo_mantencion (insumo_id),
  CONSTRAINT ck_invinsmant_stock CHECK (stock_disponible >= 0)
);

CREATE TABLE detalle_visita_insumo (
  visita_id      NUMBER NOT NULL,
  insumo_id      NUMBER NOT NULL,
  cantidad       NUMBER NOT NULL,
  costo_unitario NUMBER(10,2) NOT NULL,
  CONSTRAINT pk_detalle_visita_insumo PRIMARY KEY (visita_id, insumo_id),
  CONSTRAINT fk_detvisins_visita FOREIGN KEY (visita_id) REFERENCES visita_tecnica (visita_id),
  CONSTRAINT fk_detvisins_insumo FOREIGN KEY (insumo_id) REFERENCES insumo_mantencion (insumo_id),
  CONSTRAINT ck_detvisins_cantidad CHECK (cantidad > 0)
);

CREATE TABLE movimiento_insumo_mantencion (
  movimiento_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  bodega_id     NUMBER NOT NULL,
  insumo_id     NUMBER NOT NULL,
  tipo          VARCHAR2(10) NOT NULL,
  cantidad      NUMBER NOT NULL,
  fecha         DATE DEFAULT SYSDATE NOT NULL,
  motivo        VARCHAR2(200),
  CONSTRAINT pk_movinsmant PRIMARY KEY (movimiento_id),
  CONSTRAINT fk_movinsmant_bodega FOREIGN KEY (bodega_id) REFERENCES bodega_mantencion (bodega_id),
  CONSTRAINT fk_movinsmant_insumo FOREIGN KEY (insumo_id) REFERENCES insumo_mantencion (insumo_id),
  CONSTRAINT ck_movinsmant_tipo CHECK (tipo IN ('INGRESO','SALIDA','AJUSTE'))
);

-- resena_edificio se conserva (a diferencia de otras tablas de postventa
-- del caso): RN8 depende explícitamente de ella.
CREATE TABLE resena_edificio (
  resena_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
  arrendatario_id NUMBER NOT NULL,
  edificio_id     NUMBER NOT NULL,
  puntaje         NUMBER(1) NOT NULL,
  comentario      VARCHAR2(300),
  fecha           DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_resena_edificio PRIMARY KEY (resena_id),
  CONSTRAINT uq_resena_arrendatario_edificio UNIQUE (arrendatario_id, edificio_id),
  CONSTRAINT fk_resedif_arrendatario FOREIGN KEY (arrendatario_id) REFERENCES arrendatario (arrendatario_id),
  CONSTRAINT fk_resedif_edificio FOREIGN KEY (edificio_id) REFERENCES edificio (edificio_id),
  CONSTRAINT ck_resedif_puntaje CHECK (puntaje BETWEEN 1 AND 5)
);

CREATE TABLE movimiento_confianza (
  movimiento_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
  arrendatario_id NUMBER NOT NULL,
  contrato_id     NUMBER,
  tipo            VARCHAR2(10) NOT NULL,
  puntos          NUMBER(6) NOT NULL,
  fecha           DATE DEFAULT SYSDATE NOT NULL,
  descripcion     VARCHAR2(200),
  CONSTRAINT pk_movimiento_confianza PRIMARY KEY (movimiento_id),
  CONSTRAINT fk_movconf_arrendatario FOREIGN KEY (arrendatario_id) REFERENCES arrendatario (arrendatario_id),
  CONSTRAINT fk_movconf_contrato FOREIGN KEY (contrato_id) REFERENCES contrato_arriendo (contrato_id),
  CONSTRAINT ck_movconf_tipo CHECK (tipo IN ('POSITIVO','NEGATIVO')),
  CONSTRAINT ck_movconf_puntos CHECK (puntos > 0)
);

-- ------------------------------------------------------------
-- Datos de ejemplo
-- ------------------------------------------------------------

INSERT INTO comuna (comuna_id, nombre) VALUES (1, 'Nunoa');
INSERT INTO comuna (comuna_id, nombre) VALUES (2, 'Providencia');
INSERT INTO comuna (comuna_id, nombre) VALUES (3, 'Macul');
INSERT INTO comuna (comuna_id, nombre) VALUES (4, 'Vina del Mar');
INSERT INTO comuna (comuna_id, nombre) VALUES (5, 'Concepcion');

INSERT INTO nivel_confianza (nivel_id, nombre, puntos_minimos, beneficio_pct) VALUES (1, 'NUEVO', 0, 0);
INSERT INTO nivel_confianza (nivel_id, nombre, puntos_minimos, beneficio_pct) VALUES (2, 'CONFIABLE', 20, 3);
INSERT INTO nivel_confianza (nivel_id, nombre, puntos_minimos, beneficio_pct) VALUES (3, 'PREMIUM', 50, 7);

INSERT INTO arrendatario (arrendatario_id, nombre, email, telefono, comuna_id, nivel_id, fecha_registro) VALUES (1, 'Camila Rojas', 'camila.rojas@mail.cl', '+56911111111', 1, 1, DATE '2025-01-10');
INSERT INTO arrendatario (arrendatario_id, nombre, email, telefono, comuna_id, nivel_id, fecha_registro) VALUES (2, 'Diego Fuentes', 'diego.fuentes@mail.cl', '+56922222222', 2, 1, DATE '2025-01-15');
INSERT INTO arrendatario (arrendatario_id, nombre, email, telefono, comuna_id, nivel_id, fecha_registro) VALUES (3, 'Valentina Soto', 'valentina.soto@mail.cl', '+56933333333', 1, 1, DATE '2025-02-01');
INSERT INTO arrendatario (arrendatario_id, nombre, email, telefono, comuna_id, nivel_id, fecha_registro) VALUES (4, 'Matias Herrera', 'matias.herrera@mail.cl', '+56944444444', 4, 1, DATE '2025-02-20');
INSERT INTO arrendatario (arrendatario_id, nombre, email, telefono, comuna_id, nivel_id, fecha_registro) VALUES (5, 'Josefa Vera', 'josefa.vera@mail.cl', '+56955555555', 4, 1, DATE '2025-03-05');
INSERT INTO arrendatario (arrendatario_id, nombre, email, telefono, comuna_id, nivel_id, fecha_registro) VALUES (6, 'Tomas Aguilar', 'tomas.aguilar@mail.cl', '+56966666666', 5, 1, DATE '2025-03-18');
INSERT INTO arrendatario (arrendatario_id, nombre, email, telefono, comuna_id, nivel_id, fecha_registro) VALUES (7, 'Isidora Campos', 'isidora.campos@mail.cl', '+56977777777', 1, 1, DATE '2024-05-02');
INSERT INTO arrendatario (arrendatario_id, nombre, email, telefono, comuna_id, nivel_id, fecha_registro) VALUES (8, 'Benjamin Nunez', 'benjamin.nunez@mail.cl', '+56988888888', 2, 1, DATE '2025-04-15');

INSERT INTO propietario (propietario_id, nombre, email, telefono) VALUES (1, 'Rosa Miranda', 'rosa.miranda@mail.cl', '+56977000001');
INSERT INTO propietario (propietario_id, nombre, email, telefono) VALUES (2, 'Luis Caceres', 'luis.caceres@mail.cl', '+56977000002');
INSERT INTO propietario (propietario_id, nombre, email, telefono) VALUES (3, 'Andrea Pinto', 'andrea.pinto@mail.cl', '+56977000003');
INSERT INTO propietario (propietario_id, nombre, email, telefono) VALUES (4, 'Jorge Salinas', 'jorge.salinas@mail.cl', '+56977000004');
INSERT INTO propietario (propietario_id, nombre, email, telefono) VALUES (5, 'Marcela Torres', 'marcela.torres@mail.cl', '+56977000005');
INSERT INTO propietario (propietario_id, nombre, email, telefono) VALUES (6, 'Cristobal Munoz', 'cristobal.munoz@mail.cl', '+56977000006');

INSERT INTO tecnico (tecnico_id, nombre, especialidad, comuna_base_id, disponible, rating_promedio) VALUES (1, 'Ruben Diaz', 'GASFITERIA', 1, 'S', 4.50);
INSERT INTO tecnico (tecnico_id, nombre, especialidad, comuna_base_id, disponible, rating_promedio) VALUES (2, 'Camila Reyes', 'ELECTRICIDAD', 1, 'S', 4.70);
INSERT INTO tecnico (tecnico_id, nombre, especialidad, comuna_base_id, disponible, rating_promedio) VALUES (3, 'Jorge Alarcon', 'CERRAJERIA', 4, 'N', 4.20);
INSERT INTO tecnico (tecnico_id, nombre, especialidad, comuna_base_id, disponible, rating_promedio) VALUES (4, 'Fernanda Leon', 'ELECTRICIDAD', 4, 'S', 4.60);
INSERT INTO tecnico (tecnico_id, nombre, especialidad, comuna_base_id, disponible, rating_promedio) VALUES (5, 'Matias Bravo', 'CERRAJERIA', 5, 'S', 4.10);
INSERT INTO tecnico (tecnico_id, nombre, especialidad, comuna_base_id, disponible, rating_promedio) VALUES (6, 'Sofia Vergara', 'PINTURA', 5, 'S', 4.80);

INSERT INTO edificio (edificio_id, nombre, comuna_id, direccion) VALUES (1, 'Edificio Los Nogales', 1, 'Av. Irarrazaval 3400');
INSERT INTO edificio (edificio_id, nombre, comuna_id, direccion) VALUES (2, 'Edificio Vista Parque', 2, 'Av. Providencia 2200');
INSERT INTO edificio (edificio_id, nombre, comuna_id, direccion) VALUES (3, 'Edificio Marina Sur', 4, 'Av. San Martin 550');
INSERT INTO edificio (edificio_id, nombre, comuna_id, direccion) VALUES (4, 'Edificio Bio Bio Plaza', 5, 'Av. Paicavi 1200');

-- Unidades: 1=U101,2=U102,3=U103,4=U201,5=U202,6=U203,7=U301,8=U302,9=U303,10=U401,11=U402,12=U403 (categoria en texto directo)
INSERT INTO unidad (unidad_id, edificio_id, categoria, propietario_id, numero_unidad, estado) VALUES (1, 1, 'Studio', 1, 'U101', 'DISPONIBLE');
INSERT INTO unidad (unidad_id, edificio_id, categoria, propietario_id, numero_unidad, estado) VALUES (2, 1, 'Un Dormitorio', 1, 'U102', 'ARRENDADA');
INSERT INTO unidad (unidad_id, edificio_id, categoria, propietario_id, numero_unidad, estado) VALUES (3, 1, 'Dos Dormitorios', 2, 'U103', 'ARRENDADA');
INSERT INTO unidad (unidad_id, edificio_id, categoria, propietario_id, numero_unidad, estado) VALUES (4, 2, 'Un Dormitorio', 2, 'U201', 'ARRENDADA');
INSERT INTO unidad (unidad_id, edificio_id, categoria, propietario_id, numero_unidad, estado) VALUES (5, 2, 'Dos Dormitorios', 3, 'U202', 'DISPONIBLE');
INSERT INTO unidad (unidad_id, edificio_id, categoria, propietario_id, numero_unidad, estado) VALUES (6, 2, 'Local Comercial', 3, 'U203', 'DISPONIBLE');
INSERT INTO unidad (unidad_id, edificio_id, categoria, propietario_id, numero_unidad, estado) VALUES (7, 3, 'Studio', 4, 'U301', 'ARRENDADA');
INSERT INTO unidad (unidad_id, edificio_id, categoria, propietario_id, numero_unidad, estado) VALUES (8, 3, 'Un Dormitorio', 4, 'U302', 'DISPONIBLE');
INSERT INTO unidad (unidad_id, edificio_id, categoria, propietario_id, numero_unidad, estado) VALUES (9, 3, 'Oficina', 5, 'U303', 'ARRENDADA');
INSERT INTO unidad (unidad_id, edificio_id, categoria, propietario_id, numero_unidad, estado) VALUES (10, 4, 'Dos Dormitorios', 5, 'U401', 'ARRENDADA');
INSERT INTO unidad (unidad_id, edificio_id, categoria, propietario_id, numero_unidad, estado) VALUES (11, 4, 'Studio', 6, 'U402', 'DISPONIBLE');
INSERT INTO unidad (unidad_id, edificio_id, categoria, propietario_id, numero_unidad, estado) VALUES (12, 4, 'Un Dormitorio', 6, 'U403', 'MANTENCION');

INSERT INTO amenidad (amenidad_id, edificio_id, nombre) VALUES (1, 1, 'Gimnasio');
INSERT INTO amenidad (amenidad_id, edificio_id, nombre) VALUES (2, 1, 'Salon de Eventos');
INSERT INTO amenidad (amenidad_id, edificio_id, nombre) VALUES (3, 2, 'Gimnasio');
INSERT INTO amenidad (amenidad_id, edificio_id, nombre) VALUES (4, 2, 'Quincho');
INSERT INTO amenidad (amenidad_id, edificio_id, nombre) VALUES (5, 3, 'Piscina');
INSERT INTO amenidad (amenidad_id, edificio_id, nombre) VALUES (6, 3, 'Salon de Eventos');
INSERT INTO amenidad (amenidad_id, edificio_id, nombre) VALUES (7, 4, 'Gimnasio');
INSERT INTO amenidad (amenidad_id, edificio_id, nombre) VALUES (8, 4, 'Estacionamiento Visitas');

-- Contratos: 6 VIGENTE (uno por unidad ARRENDADA) + 2 historicos sobre unidades hoy DISPONIBLE
INSERT INTO contrato_arriendo (contrato_id, unidad_id, arrendatario_id, agente_nombre, fecha_inicio, fecha_termino, monto_mensual, estado) VALUES (1, 2, 1, 'Pedro Salinas', DATE '2025-01-01', DATE '2025-12-31', 350000, 'VIGENTE');
INSERT INTO contrato_arriendo (contrato_id, unidad_id, arrendatario_id, agente_nombre, fecha_inicio, fecha_termino, monto_mensual, estado) VALUES (2, 3, 2, 'Pedro Salinas', DATE '2025-02-01', DATE '2026-01-31', 480000, 'VIGENTE');
INSERT INTO contrato_arriendo (contrato_id, unidad_id, arrendatario_id, agente_nombre, fecha_inicio, fecha_termino, monto_mensual, estado) VALUES (3, 4, 3, 'Carolina Vidal', DATE '2025-01-15', DATE '2025-12-14', 400000, 'VIGENTE');
INSERT INTO contrato_arriendo (contrato_id, unidad_id, arrendatario_id, agente_nombre, fecha_inicio, fecha_termino, monto_mensual, estado) VALUES (4, 7, 4, 'Carolina Vidal', DATE '2025-03-01', DATE '2026-02-28', 300000, 'VIGENTE');
INSERT INTO contrato_arriendo (contrato_id, unidad_id, arrendatario_id, agente_nombre, fecha_inicio, fecha_termino, monto_mensual, estado) VALUES (5, 9, 5, 'Pedro Salinas', DATE '2025-01-01', DATE '2025-12-31', 550000, 'VIGENTE');
INSERT INTO contrato_arriendo (contrato_id, unidad_id, arrendatario_id, agente_nombre, fecha_inicio, fecha_termino, monto_mensual, estado) VALUES (6, 10, 6, 'Carolina Vidal', DATE '2025-02-15', DATE '2026-02-14', 420000, 'VIGENTE');
INSERT INTO contrato_arriendo (contrato_id, unidad_id, arrendatario_id, agente_nombre, fecha_inicio, fecha_termino, monto_mensual, estado) VALUES (7, 1, 7, 'Pedro Salinas', DATE '2024-06-01', DATE '2024-12-31', 320000, 'FINALIZADO');
INSERT INTO contrato_arriendo (contrato_id, unidad_id, arrendatario_id, agente_nombre, fecha_inicio, fecha_termino, monto_mensual, estado) VALUES (8, 5, 8, 'Carolina Vidal', DATE '2025-05-01', DATE '2026-04-30', 380000, 'CANCELADO');

-- pago_arriendo: medio_pago ahora es texto directo (NULL cuando aun no se paga)
INSERT INTO pago_arriendo (pago_id, contrato_id, periodo, monto, estado, fecha_vencimiento, fecha_pago, medio_pago) VALUES (1, 1, '2025-03', 350000, 'PAGADO', DATE '2025-03-05', DATE '2025-03-04', 'WEBPAY');
INSERT INTO pago_arriendo (pago_id, contrato_id, periodo, monto, estado, fecha_vencimiento, fecha_pago, medio_pago) VALUES (2, 1, '2025-04', 350000, 'PAGADO', DATE '2025-04-05', DATE '2025-04-05', 'WEBPAY');
INSERT INTO pago_arriendo (pago_id, contrato_id, periodo, monto, estado, fecha_vencimiento, fecha_pago, medio_pago) VALUES (3, 1, '2025-05', 350000, 'PAGADO', DATE '2025-05-05', DATE '2025-05-03', 'WEBPAY');
INSERT INTO pago_arriendo (pago_id, contrato_id, periodo, monto, estado, fecha_vencimiento, fecha_pago, medio_pago) VALUES (4, 1, '2025-06', 350000, 'PENDIENTE', DATE '2025-06-05', NULL, NULL);
INSERT INTO pago_arriendo (pago_id, contrato_id, periodo, monto, estado, fecha_vencimiento, fecha_pago, medio_pago) VALUES (5, 2, '2025-05', 480000, 'ATRASADO', DATE '2025-05-05', NULL, NULL);
INSERT INTO pago_arriendo (pago_id, contrato_id, periodo, monto, estado, fecha_vencimiento, fecha_pago, medio_pago) VALUES (6, 2, '2025-06', 480000, 'PENDIENTE', DATE '2025-06-05', NULL, NULL);
INSERT INTO pago_arriendo (pago_id, contrato_id, periodo, monto, estado, fecha_vencimiento, fecha_pago, medio_pago) VALUES (7, 3, '2025-06', 400000, 'PENDIENTE', DATE '2025-06-15', NULL, NULL);
INSERT INTO pago_arriendo (pago_id, contrato_id, periodo, monto, estado, fecha_vencimiento, fecha_pago, medio_pago) VALUES (8, 4, '2025-05', 300000, 'PAGADO', DATE '2025-05-01', DATE '2025-05-02', 'TRANSFERENCIA');
INSERT INTO pago_arriendo (pago_id, contrato_id, periodo, monto, estado, fecha_vencimiento, fecha_pago, medio_pago) VALUES (9, 4, '2025-06', 300000, 'PAGADO', DATE '2025-06-01', DATE '2025-06-01', 'TRANSFERENCIA');
INSERT INTO pago_arriendo (pago_id, contrato_id, periodo, monto, estado, fecha_vencimiento, fecha_pago, medio_pago) VALUES (10, 5, '2025-05', 550000, 'PAGADO', DATE '2025-05-01', DATE '2025-05-01', 'EFECTIVO');
INSERT INTO pago_arriendo (pago_id, contrato_id, periodo, monto, estado, fecha_vencimiento, fecha_pago, medio_pago) VALUES (11, 5, '2025-06', 550000, 'PENDIENTE', DATE '2025-06-01', NULL, NULL);
INSERT INTO pago_arriendo (pago_id, contrato_id, periodo, monto, estado, fecha_vencimiento, fecha_pago, medio_pago) VALUES (12, 6, '2025-06', 420000, 'ATRASADO', DATE '2025-06-15', NULL, NULL);

INSERT INTO reserva_amenidad (reserva_id, amenidad_id, arrendatario_id, fecha, hora_inicio, hora_fin, estado) VALUES (1, 2, 1, DATE '2025-06-20', 10, 13, 'CONFIRMADA');
INSERT INTO reserva_amenidad (reserva_id, amenidad_id, arrendatario_id, fecha, hora_inicio, hora_fin, estado) VALUES (2, 4, 3, DATE '2025-06-21', 18, 22, 'CONFIRMADA');
INSERT INTO reserva_amenidad (reserva_id, amenidad_id, arrendatario_id, fecha, hora_inicio, hora_fin, estado) VALUES (3, 6, 4, DATE '2025-06-22', 15, 19, 'CONFIRMADA');
INSERT INTO reserva_amenidad (reserva_id, amenidad_id, arrendatario_id, fecha, hora_inicio, hora_fin, estado) VALUES (4, 7, 6, DATE '2025-06-15', 7, 8, 'CONFIRMADA');
INSERT INTO reserva_amenidad (reserva_id, amenidad_id, arrendatario_id, fecha, hora_inicio, hora_fin, estado) VALUES (5, 1, 1, DATE '2025-06-18', 7, 8, 'CONFIRMADA');
INSERT INTO reserva_amenidad (reserva_id, amenidad_id, arrendatario_id, fecha, hora_inicio, hora_fin, estado) VALUES (6, 3, 3, DATE '2025-06-19', 17, 18, 'CONFIRMADA');

INSERT INTO solicitud_mantencion (solicitud_id, unidad_id, arrendatario_id, tipo_problema, descripcion, prioridad, estado, tecnico_id, fecha_solicitud) VALUES (1, 2, 1, 'GASFITERIA', 'Fuga en llave de cocina', 'ALTA', 'ASIGNADA', 1, DATE '2025-06-10');
INSERT INTO solicitud_mantencion (solicitud_id, unidad_id, arrendatario_id, tipo_problema, descripcion, prioridad, estado, tecnico_id, fecha_solicitud) VALUES (2, 3, 2, 'ELECTRICIDAD', 'Enchufe no funciona', 'MEDIA', 'SOLICITADA', NULL, DATE '2025-06-11');
INSERT INTO solicitud_mantencion (solicitud_id, unidad_id, arrendatario_id, tipo_problema, descripcion, prioridad, estado, tecnico_id, fecha_solicitud) VALUES (3, 4, 3, 'CERRAJERIA', 'Cerradura de entrada trabada', 'ALTA', 'RESUELTA', 3, DATE '2025-06-05');
INSERT INTO solicitud_mantencion (solicitud_id, unidad_id, arrendatario_id, tipo_problema, descripcion, prioridad, estado, tecnico_id, fecha_solicitud) VALUES (4, 7, 4, 'PINTURA', 'Filtracion de humedad en muro', 'BAJA', 'SOLICITADA', NULL, DATE '2025-06-12');
INSERT INTO solicitud_mantencion (solicitud_id, unidad_id, arrendatario_id, tipo_problema, descripcion, prioridad, estado, tecnico_id, fecha_solicitud) VALUES (5, 9, 5, 'ELECTRICIDAD', 'Interruptor no enciende luz', 'MEDIA', 'EN_PROCESO', 4, DATE '2025-06-08');
INSERT INTO solicitud_mantencion (solicitud_id, unidad_id, arrendatario_id, tipo_problema, descripcion, prioridad, estado, tecnico_id, fecha_solicitud) VALUES (6, 10, 6, 'GASFITERIA', 'Baja presion de agua', 'BAJA', 'CANCELADA', NULL, DATE '2025-06-09');
INSERT INTO solicitud_mantencion (solicitud_id, unidad_id, arrendatario_id, tipo_problema, descripcion, prioridad, estado, tecnico_id, fecha_solicitud) VALUES (7, 2, 1, 'ELECTRICIDAD', 'Corte de luz intermitente', 'MEDIA', 'SOLICITADA', NULL, DATE '2025-06-13');
INSERT INTO solicitud_mantencion (solicitud_id, unidad_id, arrendatario_id, tipo_problema, descripcion, prioridad, estado, tecnico_id, fecha_solicitud) VALUES (8, 3, 2, 'CERRAJERIA', 'Llave de repuesto para closet', 'BAJA', 'RESUELTA', 5, DATE '2025-06-06');

INSERT INTO visita_tecnica (visita_id, solicitud_id, tecnico_id, fecha_visita, estado, diagnostico, costo_reparacion) VALUES (1, 1, 1, DATE '2025-06-11', 'PLANIFICADA', NULL, NULL);
INSERT INTO visita_tecnica (visita_id, solicitud_id, tecnico_id, fecha_visita, estado, diagnostico, costo_reparacion) VALUES (2, 3, 3, DATE '2025-06-06', 'COMPLETADA', 'Cerradura lubricada y ajustada', 8000);
INSERT INTO visita_tecnica (visita_id, solicitud_id, tecnico_id, fecha_visita, estado, diagnostico, costo_reparacion) VALUES (3, 5, 4, DATE '2025-06-09', 'EN_CURSO', NULL, NULL);
INSERT INTO visita_tecnica (visita_id, solicitud_id, tecnico_id, fecha_visita, estado, diagnostico, costo_reparacion) VALUES (4, 8, 5, DATE '2025-06-07', 'COMPLETADA', 'Se entrego llave de repuesto', 5000);
INSERT INTO visita_tecnica (visita_id, solicitud_id, tecnico_id, fecha_visita, estado, diagnostico, costo_reparacion) VALUES (5, 7, 2, DATE '2025-06-14', 'PLANIFICADA', NULL, NULL);

INSERT INTO insumo_mantencion (insumo_id, nombre, costo_unitario) VALUES (1, 'Llave de paso', 8000);
INSERT INTO insumo_mantencion (insumo_id, nombre, costo_unitario) VALUES (2, 'Cable electrico (metro)', 800);
INSERT INTO insumo_mantencion (insumo_id, nombre, costo_unitario) VALUES (3, 'Ceramica (unidad)', 1500);
INSERT INTO insumo_mantencion (insumo_id, nombre, costo_unitario) VALUES (4, 'Pintura latex (galon)', 18000);
INSERT INTO insumo_mantencion (insumo_id, nombre, costo_unitario) VALUES (5, 'Cerradura estandar', 25000);
INSERT INTO insumo_mantencion (insumo_id, nombre, costo_unitario) VALUES (6, 'Sellante silicona', 4000);
INSERT INTO insumo_mantencion (insumo_id, nombre, costo_unitario) VALUES (7, 'Interruptor electrico', 3500);
INSERT INTO insumo_mantencion (insumo_id, nombre, costo_unitario) VALUES (8, 'Guantes de trabajo (par)', 2500);

INSERT INTO bodega_mantencion (bodega_id, nombre, comuna_id) VALUES (1, 'Bodega Mantencion Nunoa', 1);
INSERT INTO bodega_mantencion (bodega_id, nombre, comuna_id) VALUES (2, 'Bodega Mantencion Vina del Mar', 4);
INSERT INTO bodega_mantencion (bodega_id, nombre, comuna_id) VALUES (3, 'Bodega Mantencion Concepcion', 5);

INSERT INTO inventario_insumo_mantencion (bodega_id, insumo_id, stock_disponible) VALUES (1, 1, 20);
INSERT INTO inventario_insumo_mantencion (bodega_id, insumo_id, stock_disponible) VALUES (1, 2, 100);
INSERT INTO inventario_insumo_mantencion (bodega_id, insumo_id, stock_disponible) VALUES (1, 5, 8);
INSERT INTO inventario_insumo_mantencion (bodega_id, insumo_id, stock_disponible) VALUES (1, 7, 25);
INSERT INTO inventario_insumo_mantencion (bodega_id, insumo_id, stock_disponible) VALUES (1, 8, 35);
INSERT INTO inventario_insumo_mantencion (bodega_id, insumo_id, stock_disponible) VALUES (2, 3, 50);
INSERT INTO inventario_insumo_mantencion (bodega_id, insumo_id, stock_disponible) VALUES (2, 4, 15);
INSERT INTO inventario_insumo_mantencion (bodega_id, insumo_id, stock_disponible) VALUES (2, 6, 30);
INSERT INTO inventario_insumo_mantencion (bodega_id, insumo_id, stock_disponible) VALUES (2, 1, 10);
INSERT INTO inventario_insumo_mantencion (bodega_id, insumo_id, stock_disponible) VALUES (3, 5, 12);
INSERT INTO inventario_insumo_mantencion (bodega_id, insumo_id, stock_disponible) VALUES (3, 8, 40);
INSERT INTO inventario_insumo_mantencion (bodega_id, insumo_id, stock_disponible) VALUES (3, 6, 18);

INSERT INTO detalle_visita_insumo (visita_id, insumo_id, cantidad, costo_unitario) VALUES (2, 5, 1, 25000);
INSERT INTO detalle_visita_insumo (visita_id, insumo_id, cantidad, costo_unitario) VALUES (4, 1, 1, 8000);

-- Los INGRESO ahora se registran como reposición directa (ya no existe
-- una tabla ORDEN_ABASTECIMIENTO_MANTENCION/PROVEEDOR formal detrás).
INSERT INTO movimiento_insumo_mantencion (movimiento_id, bodega_id, insumo_id, tipo, cantidad, fecha, motivo) VALUES (1, 1, 1, 'INGRESO', 25, DATE '2025-03-01', 'Reposicion de stock');
INSERT INTO movimiento_insumo_mantencion (movimiento_id, bodega_id, insumo_id, tipo, cantidad, fecha, motivo) VALUES (2, 1, 1, 'SALIDA', 5, DATE '2025-05-20', 'Uso en visitas tecnicas');
INSERT INTO movimiento_insumo_mantencion (movimiento_id, bodega_id, insumo_id, tipo, cantidad, fecha, motivo) VALUES (3, 1, 5, 'INGRESO', 10, DATE '2025-03-03', 'Reposicion de stock');
INSERT INTO movimiento_insumo_mantencion (movimiento_id, bodega_id, insumo_id, tipo, cantidad, fecha, motivo) VALUES (4, 1, 5, 'AJUSTE', -2, DATE '2025-05-22', 'Cerradura danada');
INSERT INTO movimiento_insumo_mantencion (movimiento_id, bodega_id, insumo_id, tipo, cantidad, fecha, motivo) VALUES (5, 3, 5, 'INGRESO', 15, DATE '2025-03-05', 'Reposicion de stock');
INSERT INTO movimiento_insumo_mantencion (movimiento_id, bodega_id, insumo_id, tipo, cantidad, fecha, motivo) VALUES (6, 3, 5, 'SALIDA', 3, DATE '2025-05-25', 'Uso en visitas tecnicas');

INSERT INTO resena_edificio (resena_id, arrendatario_id, edificio_id, puntaje, comentario, fecha) VALUES (1, 1, 1, 5, 'Excelente conserje y buena mantencion', DATE '2025-04-01');
INSERT INTO resena_edificio (resena_id, arrendatario_id, edificio_id, puntaje, comentario, fecha) VALUES (2, 2, 1, 4, 'Buena ubicacion, ascensor lento', DATE '2025-04-05');
INSERT INTO resena_edificio (resena_id, arrendatario_id, edificio_id, puntaje, comentario, fecha) VALUES (3, 3, 2, 4, 'Tranquilo y bien ubicado', DATE '2025-04-10');
INSERT INTO resena_edificio (resena_id, arrendatario_id, edificio_id, puntaje, comentario, fecha) VALUES (4, 4, 3, 5, 'Vista al mar increible', DATE '2025-04-12');
INSERT INTO resena_edificio (resena_id, arrendatario_id, edificio_id, puntaje, comentario, fecha) VALUES (5, 5, 3, 3, 'Buena vista pero mantencion lenta', DATE '2025-04-15');
INSERT INTO resena_edificio (resena_id, arrendatario_id, edificio_id, puntaje, comentario, fecha) VALUES (6, 6, 4, 4, 'Buena relacion precio-calidad', DATE '2025-04-18');

-- Puntos de confianza: 5 puntos por cada pago registrado a tiempo (historico, ya cargado)
INSERT INTO movimiento_confianza (movimiento_id, arrendatario_id, contrato_id, tipo, puntos, fecha, descripcion) VALUES (1, 1, 1, 'POSITIVO', 5, DATE '2025-03-04', 'Pago a tiempo periodo 2025-03');
INSERT INTO movimiento_confianza (movimiento_id, arrendatario_id, contrato_id, tipo, puntos, fecha, descripcion) VALUES (2, 1, 1, 'POSITIVO', 5, DATE '2025-04-05', 'Pago a tiempo periodo 2025-04');
INSERT INTO movimiento_confianza (movimiento_id, arrendatario_id, contrato_id, tipo, puntos, fecha, descripcion) VALUES (3, 1, 1, 'POSITIVO', 5, DATE '2025-05-03', 'Pago a tiempo periodo 2025-05');
INSERT INTO movimiento_confianza (movimiento_id, arrendatario_id, contrato_id, tipo, puntos, fecha, descripcion) VALUES (4, 4, 4, 'POSITIVO', 5, DATE '2025-05-02', 'Pago a tiempo periodo 2025-05');
INSERT INTO movimiento_confianza (movimiento_id, arrendatario_id, contrato_id, tipo, puntos, fecha, descripcion) VALUES (5, 4, 4, 'POSITIVO', 5, DATE '2025-06-01', 'Pago a tiempo periodo 2025-06');
INSERT INTO movimiento_confianza (movimiento_id, arrendatario_id, contrato_id, tipo, puntos, fecha, descripcion) VALUES (6, 5, 5, 'POSITIVO', 5, DATE '2025-05-01', 'Pago a tiempo periodo 2025-05');

COMMIT;

-- Nota sobre secuencias de identidad: al haberse insertado los identificadores
-- de forma explicita con columnas GENERATED BY DEFAULT AS IDENTITY, conviene
-- sincronizar el contador interno antes de insertar nuevas filas sin indicar
-- el id, ajustando el valor inicial al maximo utilizado mas uno, en cada una
-- de las 20 tablas que se vaya a seguir poblando.

-- Verificacion rapida de la carga (20 tablas)
SELECT 'COMUNA' AS tabla, COUNT(*) AS filas FROM comuna
UNION ALL SELECT 'NIVEL_CONFIANZA', COUNT(*) FROM nivel_confianza
UNION ALL SELECT 'ARRENDATARIO', COUNT(*) FROM arrendatario
UNION ALL SELECT 'PROPIETARIO', COUNT(*) FROM propietario
UNION ALL SELECT 'TECNICO', COUNT(*) FROM tecnico
UNION ALL SELECT 'EDIFICIO', COUNT(*) FROM edificio
UNION ALL SELECT 'UNIDAD', COUNT(*) FROM unidad
UNION ALL SELECT 'AMENIDAD', COUNT(*) FROM amenidad
UNION ALL SELECT 'CONTRATO_ARRIENDO', COUNT(*) FROM contrato_arriendo
UNION ALL SELECT 'PAGO_ARRIENDO', COUNT(*) FROM pago_arriendo
UNION ALL SELECT 'RESERVA_AMENIDAD', COUNT(*) FROM reserva_amenidad
UNION ALL SELECT 'SOLICITUD_MANTENCION', COUNT(*) FROM solicitud_mantencion
UNION ALL SELECT 'VISITA_TECNICA', COUNT(*) FROM visita_tecnica
UNION ALL SELECT 'INSUMO_MANTENCION', COUNT(*) FROM insumo_mantencion
UNION ALL SELECT 'BODEGA_MANTENCION', COUNT(*) FROM bodega_mantencion
UNION ALL SELECT 'INVENTARIO_INSUMO_MANTENCION', COUNT(*) FROM inventario_insumo_mantencion
UNION ALL SELECT 'DETALLE_VISITA_INSUMO', COUNT(*) FROM detalle_visita_insumo
UNION ALL SELECT 'MOVIMIENTO_INSUMO_MANTENCION', COUNT(*) FROM movimiento_insumo_mantencion
UNION ALL SELECT 'RESENA_EDIFICIO', COUNT(*) FROM resena_edificio
UNION ALL SELECT 'MOVIMIENTO_CONFIANZA', COUNT(*) FROM movimiento_confianza;
